name: dbt CI Check

on:
  pull_request:
    branches: [ main ]

jobs:
  dbt_run_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out repository code
        uses: actions/checkout@v3

      - name: 2. Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 3. Install dbt dependencies
        run: pip install dbt-core dbt-snowflake

      - name: 4. Configure dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "
          flight_tracker_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ${{ secrets.SNOWFLAKE_ROLE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                schema: transformed_ci_${{ github.run_number }}
                threads: 4
          " > ~/.dbt/profiles.yml

      - name: 5. Run dbt commands
        run: |
          dbt deps
          dbt run
          dbt test
